# ShaderMake Integration for HLVM Engine
# 
# This module integrates NVIDIA Donut's ShaderMake tool into PyCMake build system.
# ShaderMake compiles HLSL shaders to SPIR-V binary blobs with NVSP header + permutation table.
# 
# Usage:
#   from ShaderMakeBuild import create_deferred_shading_shadermake
#   deferred_shaders = create_deferred_shading_shadermake("TestDeferredShading")
#   runtime_project.modules.append(deferred_shaders)
#
# Required inputs:
#   - ShaderMake binary at $CMAKE_SOURCE_DIR/../../Binary/GNULinux-x64/ShaderMake/bin/ShaderMake
#   - slangc compiler at $VULKAN_SDK/bin/slangc
#   - HLSL source files in Test/TestDeferredShading_Data/
#   - ShaderMake config file (.cfg)

from PyCMake.cmakecpp import *

# ShaderMake binary path (relative to CMAKE_SOURCE_DIR)
# CMAKE_SOURCE_DIR for Runtime = Engine/Source/Runtime, so need to go up 2 levels to reach Engine/Binary
SHADERMAKE_BINARY_PATH = "../../Binary/GNULinux-x64/ShaderMake/bin/ShaderMake"

# Default Vulkan register shifts for NVRHI compatibility
# These match NVRHI_DEFAULT_VK_REGISTER_OFFSETS in Donut's compileshaders.cmake
NVRHI_VK_REGISTER_SHIFTS = "--tRegShift 0 --sRegShift 128 --bRegShift 256 --uRegShift 384"


class ShaderMakeModule:
    """
    ShaderMake integration module for PyCMake.
    
    Compiles HLSL shaders to SPIR-V binary blobs using ShaderMake tool.
    The blobs contain NVSP header + permutation table + SPIR-V data,
    which can be loaded at runtime via ShaderMake::FindPermutationInBlob().
    """
    
    def __init__(
        self,
        target_name: str,
        config_file_cmake: str,
        shader_sources_cmake: list,
        output_dir_cmake: str,
        include_dirs_cmake: list = None,
        project_name: str = "HLVM",
        slang_options: str = ""
    ):
        self.target_name = target_name
        self.config_file_cmake = config_file_cmake
        self.shader_sources_cmake = shader_sources_cmake
        self.output_dir_cmake = output_dir_cmake
        self.include_dirs_cmake = include_dirs_cmake or []
        self.project_name = project_name
        self.slang_options = slang_options
        
    def dump(self, fp):
        # Build include directories CMake code - one per line
        include_dirs_lines = []
        for inc_dir in self.include_dirs_cmake:
            include_dirs_lines.append('    -I "' + inc_dir + '"')
        include_dirs_code = "\n".join(include_dirs_lines) + "\n"
        
        slang_opts = " " + self.slang_options if self.slang_options else ""
        
        # Build shader sources DEPENDS - space-separated quoted paths
        sources_depends = " ".join(['"' + s + '"' for s in self.shader_sources_cmake])
        
        # Build the CMake code using string concatenation to avoid f-string issues with ${} vars
        cmake_code = (
            "# ShaderMake compilation for " + self.target_name + "\n"
            "# Auto-generated by ShaderMakeBuild.py\n"
            "\n"
            "# ShaderMake binary and compiler paths\n"
            'set(SHADERMAKE_BIN "${CMAKE_SOURCE_DIR}/' + SHADERMAKE_BINARY_PATH + '")\n'
            'set(SLANG_COMPILER "$ENV{VULKAN_SDK}/bin/slangc")\n'
            "\n"
            "# Verify ShaderMake exists\n"
            'if(NOT EXISTS "${SHADERMAKE_BIN}")\n'
            '    message(FATAL_ERROR "ShaderMake not found at ${SHADERMAKE_BIN}")\n'
            "endif()\n"
            "\n"
            "# Verify slangc exists\n"
            'if(NOT EXISTS "${SLANG_COMPILER}")\n'
            '    message(FATAL_ERROR "slangc not found at ${SLANG_COMPILER}. Set VULKAN_SDK environment variable.")\n'
            "endif()\n"
            "\n"
            "# ShaderMake compilation command\n"
            "set(SHADERMAKE_CMD \n"
            '    ${CMAKE_COMMAND} -E env "LD_LIBRARY_PATH=$ENV{VULKAN_SDK}/lib:$ENV{LD_LIBRARY_PATH}" \n'
            '    "${SHADERMAKE_BIN}"\n'
            "    -p SPIRV\n"
            "    --platform SPIRV\n"
            '    -c "' + self.config_file_cmake + '"\n'
            '    -o "' + self.output_dir_cmake + '"\n'
            "    -B\n"      # Generate .sblob blob files
            "    --outputExt .sblob\n"
            "    --force\n"
            '    --compiler "${SLANG_COMPILER}"\n'
            "    --slang\n"
            "    --slangHLSL\n"
            "    -D SPIRV\n"
            "    -D TARGET_VULKAN\n"
            "    " + NVRHI_VK_REGISTER_SHIFTS + "\n"
            "    --vulkanVersion 1.3\n"
            "    --shaderModel 6_5\n"
            "    --project " + self.project_name + "\n"
            + include_dirs_code
            + slang_opts + "\n"
            ")\n"
            "\n"
            "# Print shader compilation info\n"
            'message(STATUS "ShaderMake: Compiling shaders from ' + self.config_file_cmake + '")\n'
            'message(STATUS "ShaderMake: Output to ' + self.output_dir_cmake + '")\n'
            "\n"
            "# Create a custom target that compiles shaders\n"
            "# Note: ShaderMake handles its own incremental compilation based on timestamps\n"
            "add_custom_target(" + self.target_name + " ALL\n"
            "    COMMAND ${SHADERMAKE_CMD}\n"
            '    COMMENT "Compiling HLSL shaders with ShaderMake for ' + self.target_name + '"\n'
            "    DEPENDS\n"
            '        "${SHADERMAKE_BIN}"\n'
            '        "${SLANG_COMPILER}"\n'
            "        " + sources_depends + "\n"
            '    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"\n'
            ")\n"
        )
        
        fp.write(cmake_code)


def create_deferred_shading_shadermake(test_target_name: str) -> ShaderMakeModule:
    """Factory function to create ShaderMake module for deferred shading shaders."""
    shader_target_name = test_target_name + "_ShaderMake"
    
    # CMAKE_SOURCE_DIR for Runtime = Engine/Source/Runtime
    test_data_dir = "${CMAKE_SOURCE_DIR}/Test/TestDeferredShading_Data"
    
    # Config file is in TestDeferredShading_Data directory
    config_file = "${CMAKE_SOURCE_DIR}/Test/TestDeferredShading_Data/ShaderMake.cfg"
    
    # Shader source files (currently only Blit shaders exist as HLSL)
    shader_sources = [
        test_data_dir + "/blit_vs.hlsl",
        test_data_dir + "/blit_ps.hlsl",
    ]
    
    # Include directories (for #include <donut/shaders/...>)
    include_dirs = [
        test_data_dir,  # For #include <donut/shaders/...>
    ]
    
    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=test_data_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_Deferred",
        slang_options=""
    )


# Example usage:
#
# from ShaderMakeBuild import create_deferred_shading_shadermake
#
# # In RuntimeProject.__init__():
# deferred_shaders = create_deferred_shading_shadermake("TestDeferredShading")
# self.modules.append(deferred_shaders)


def create_full_deferred_shading2_shadermake(test_target_name: str) -> ShaderMakeModule:
    """Factory function to create ShaderMake module for TestFullDeferredShading2 shaders.
    """
    shader_target_name = test_target_name + "_ShaderMake"

    # CMAKE_SOURCE_DIR for Runtime = Engine/Source/Runtime
    test_data_dir = "${CMAKE_SOURCE_DIR}/Test/TestFullDeferredShading2_Data"

    # Config file is in TestFullDeferredShading2_Data directory
    config_file = "${CMAKE_SOURCE_DIR}/Test/TestFullDeferredShading2_Data/ShaderMake.cfg"

    # Shader source files for TestFullDeferredShading2 (including blit shaders)
    shader_sources = [
        test_data_dir + "/BlitVS.hlsl",
        test_data_dir + "/BlitPS.hlsl",
        test_data_dir + "/gbuffer_vs.hlsl",
        test_data_dir + "/gbuffer_ps.hlsl",
        test_data_dir + "/deferred_lighting_cs.hlsl",
    ]

    # Include directories
    include_dirs = [
        test_data_dir,
    ]

    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=test_data_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_FullDeferred2",
        slang_options=""
    )


def create_rt_shadows_gbuffer_shadermake(test_target_name: str) -> ShaderMakeModule:
    """Factory function to create ShaderMake module for TestRTShadowsGBuffer shaders."""
    shader_target_name = test_target_name + "_ShaderMake"

    # CMAKE_SOURCE_DIR for Runtime = Engine/Source/Runtime
    test_data_dir = "${CMAKE_SOURCE_DIR}/Test/TestRTShadowsGBuffer_Data"

    # Config file is in TestRTShadowsGBuffer_Data directory
    config_file = "${CMAKE_SOURCE_DIR}/Test/TestRTShadowsGBuffer_Data/ShaderMake.cfg"

    # Shader source files for TestRTShadowsGBuffer
    shader_sources = [
        test_data_dir + "/RTShadowsGBuffer.hlsl",
    ]

    # Include directories
    include_dirs = [
        test_data_dir,
    ]

    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=test_data_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_RTShadowsGBuffer",
        slang_options=""
    )


def create_sponza_deferred_shadermake(test_target_name: str) -> ShaderMakeModule:
    """Factory function to create ShaderMake module for TestSponzaDeferred shaders."""
    shader_target_name = test_target_name + "_ShaderMake"

    # CMAKE_SOURCE_DIR for Runtime = Engine/Source/Runtime
    test_data_dir = "${CMAKE_SOURCE_DIR}/Test/TestSponzaDeferred_Data"

    # Config file is in TestSponzaDeferred_Data directory
    config_file = "${CMAKE_SOURCE_DIR}/Test/TestSponzaDeferred_Data/ShaderMake.cfg"

    # Shader source files for TestSponzaDeferred
    shader_sources = [
        test_data_dir + "/GBufferSponzaVS.hlsl",
        test_data_dir + "/GBufferSponzaPS.hlsl",
        test_data_dir + "/SponzaDeferredLighting_cs.hlsl",
    ]

    # Include directories
    include_dirs = [
        test_data_dir,
    ]

    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=test_data_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_SponzaDeferred",
        slang_options=""
    )


def create_render_sponza_shadermake(test_target_name: str) -> ShaderMakeModule:
    """Factory function to create ShaderMake module for TestRenderSponza shaders."""
    shader_target_name = test_target_name + "_ShaderMake"

    test_data_dir = "${CMAKE_SOURCE_DIR}/Test/TestRenderSponza_Data"
    config_file = "${CMAKE_SOURCE_DIR}/Test/TestRenderSponza_Data/ShaderMake.cfg"

    shader_sources = [
        test_data_dir + "/SponzaForwardVS.hlsl",
        test_data_dir + "/SponzaForwardPS.hlsl",
    ]

    include_dirs = [
        test_data_dir,
    ]

    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=test_data_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_RenderSponza",
        slang_options=""
    )


def create_pbr_lighting_shadermake(test_target_name: str) -> ShaderMakeModule:
    """Factory function to create ShaderMake module for TestPBRLighting shaders."""
    shader_target_name = test_target_name + "_ShaderMake"

    test_data_dir = "${CMAKE_SOURCE_DIR}/Test/TestPBRLighting_Data"
    config_file = "${CMAKE_SOURCE_DIR}/Test/TestPBRLighting_Data/ShaderMake.cfg"

    shader_sources = [
        test_data_dir + "/PBRLighting_cs.hlsl",
    ]

    include_dirs = [
        test_data_dir,
    ]

    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=test_data_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_PBRLighting",
        slang_options=""
    )


def create_common_shadermake() -> ShaderMakeModule:
    """Factory function to create ShaderMake module for common shaders (BlitVS, BlitPS).

    These shaders are shared across multiple passes and located in Engine/Source/Runtime/Shader/.
    FCommonRenderPasses uses these by default; tests can override with SetShaderDataDir().
    """
    shader_target_name = "Common_ShaderMake"

    # CMAKE_SOURCE_DIR for Runtime = Engine/Source/Runtime
    shader_dir = "${CMAKE_SOURCE_DIR}/Shader"

    # Config file is in Shader directory
    config_file = "${CMAKE_SOURCE_DIR}/Shader/ShaderMake.cfg"

    # Shader source files for common shaders
    shader_sources = [
        shader_dir + "/BlitVS.hlsl",
        shader_dir + "/BlitPS.hlsl",
    ]

    # Include directories
    include_dirs = [
        shader_dir,
    ]

    return ShaderMakeModule(
        target_name=shader_target_name,
        config_file_cmake=config_file,
        shader_sources_cmake=shader_sources,
        output_dir_cmake=shader_dir,
        include_dirs_cmake=include_dirs,
        project_name="HLVM_Common",
        slang_options=""
    )